studorg/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'edukacije.views.home', name='home'),
    # url(r'^edukacije/', include('edukacije.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('user_zone.urls')),
    url(r'', include('organizer.urls')),
    url(r'', include('university.urls')),
    
    # url(r'^korisnici', include('user_zone.urls')),
    # url(r'', include('frontend.urls', app_name='frontend')) # mora biti zadnje
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

university/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import RedirectView, TemplateView

from views import *


urlpatterns = patterns('',  
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)$', CourseView.as_view(), name="course"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/posalji-mail/(?P<employee_id>\d+)$', SendMailView.as_view(), name="send_mail"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/objave$', CourseWallView.as_view(), name="course_wall"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/nova-objava$', EditPostView.as_view(), name="new_post"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/uredi-objavu/(?P<post_id>\d+)$', EditPostView.as_view(), name="edit_post"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/post-comments/$', PostCommentsView.as_view(), name="post_comments"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/add-comment/$', add_comment, name="add_comment"),
    url(r'^kolegij/(?P<course_slug>[\w-]+)-(?P<course_id>\d+)/post-files/$', PostFilesView.as_view(), name="post_files"),
    url(r'^delete-post$', delete_post, name="delete_post"),
    url(r'^delete-file$', delete_file, name="delete_file"),
    url(r'^delete-comment$', delete_comment, name="delete_comment"),
)

organizer/models.py
# -*- coding: utf-8 -*-
from django.db import models

from django.conf import settings
from django.utils.translation import ugettext as _
from user_zone.models import Student, StudentCourse
from django.template.defaultfilters import slugify
from decimal import *
from django.core.urlresolvers import reverse

class ActivityType(models.Model):
    name = models.CharField(verbose_name=u'Naziv', max_length=255)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u"Tip aktivnosti")
        verbose_name_plural = _(u"Tipovi aktivnosti")

class Activity(models.Model):
    student = models.ForeignKey(Student, verbose_name=u'Student')
    title = models.CharField(verbose_name=u'Naziv', max_length=255)
    activity_type = models.ForeignKey(ActivityType, verbose_name=u'Tip aktivnosti', null=True, blank=True)
    start = models.DateTimeField(verbose_name=u"Vrijeme početka")
    end = models.DateTimeField(verbose_name=u"Vrijeme završetka")    
    course = models.ForeignKey(StudentCourse, verbose_name=u'Kolegij', null=True, blank=True)
    description = models.TextField(verbose_name=u'Opis', null=True, blank=True)
    max_points = models.DecimalField(verbose_name=_(u"Mogući broj bodova"), default=0, max_digits = 5, decimal_places = 2)
    achieved_points = models.DecimalField(verbose_name=_(u"Ostvareni broj bodova"), default=0, max_digits = 5, decimal_places = 2)

    def __unicode__(self):
        return unicode(self.title)

    class Meta:
        verbose_name = _(u"Aktivnost")
        verbose_name_plural = _(u"Aktivnosti")

    def get_slug(self):
        return slugify(self.title)

    def save(self, *args, **kwargs):
        super(Activity, self).save(*args, **kwargs)
        update_course_points(self.course)

    def get_url(self):
        return reverse('activity', args=[slugify(self.title), self.id])

def update_course_points(course):
    activities = Activity.objects.filter(course=course)
    points = Decimal(0)
    for activity in activities:
        points += activity.achieved_points
    course.achieved_points = points
    course.save()

class Note(models.Model):
    student = models.ForeignKey(Student, verbose_name=u'Student')
    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    date = models.DateTimeField(verbose_name=u"Datum", auto_now=True)
    note = models.TextField(verbose_name=u'Bilješka')
    course = models.ForeignKey(StudentCourse, verbose_name=u'Kolegij', null=True, blank=True)
    position = models.IntegerField(verbose_name=_("Redoslijed"), default=0)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name=_(u"Bilješka")
        verbose_name_plural=_(u"Bilješke")
        ordering=('-date',)

    def get_slug(self):
        return slugify(self.name)

class ToDo(models.Model):
    student = models.ForeignKey(Student, verbose_name=u'Student')
    date = models.DateTimeField(verbose_name=u"Datum", auto_now=True)
    to_do = models.CharField(verbose_name=u'To do', max_length=255)
    course = models.ForeignKey(StudentCourse, verbose_name=u'Kolegij', null=True, blank=True)
    position = models.IntegerField(verbose_name=_("Redoslijed"), default=0)
    done = models.BooleanField(verbose_name=u'Obavljeno', default=False)

    def __unicode__(self):
        return unicode(self.to_do)

    class Meta:
        verbose_name=_(u"TO DO")
        verbose_name_plural=_(u"TO DO")
        ordering=('position',)

class Literature(models.Model):
    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    student = models.ForeignKey(Student, verbose_name=u'Student')
    course = models.ForeignKey(StudentCourse, verbose_name=u'Kolegij')
    authors = models.TextField(verbose_name=u'Autori')
    description = models.TextField(verbose_name=u'Opis', null=True, blank=True)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name=_(u"Literatura")
        verbose_name_plural=_(u"Literatura")

class Post(models.Model):
    date = models.DateTimeField(verbose_name=u"Datum", auto_now=True)
    text = models.TextField(verbose_name=u'Tekst')
    student = models.ForeignKey(Student, verbose_name=u'Student')
    course = models.ForeignKey(StudentCourse, verbose_name=u'Kolegij')

    def __unicode__(self):
        return unicode(self.text)

    class Meta:
        verbose_name=_(u"Objava")
        verbose_name_plural=_(u"Objave")
        ordering=('-date',)

class PostComment(models.Model):
    date = models.DateTimeField(verbose_name=u"Datum", auto_now=True)
    text = models.TextField(verbose_name=u'Tekst')
    student = models.ForeignKey(Student, verbose_name=u'Student')
    post = models.ForeignKey(Post, verbose_name=u'Objava')

    def __unicode__(self):
        return unicode(self.text)

    class Meta:
        verbose_name=_(u"Komentar na objavu")
        verbose_name_plural=_(u"Komentari na objavu")
        ordering=('date',)

class File(models.Model):
    root_folder = 'files'

    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    date = models.DateTimeField(verbose_name=u"Datum")
    description = models.TextField(verbose_name=u'Tekst', null=True, blank=True)
    student = models.ForeignKey(Student, verbose_name=u'Student')
    post = models.ForeignKey(Post, verbose_name=u'Objava', null=True, blank=True)
    position = models.IntegerField(verbose_name=_("Redoslijed"), default=0)
    filename = models.FileField(verbose_name=_(u"Datoteka"), upload_to='student_files', max_length=255)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name=_(u"Datoteka")
        verbose_name_plural=_(u"Datoteke")
        ordering=('position',)

university/models.py
# -*- coding: utf-8 -*-
from django.db import models

from django.utils.translation import ugettext as _

class Place(models.Model):
    zip_code = models.IntegerField(verbose_name=u'Poštanski broj')
    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    last_update = models.DateTimeField(verbose_name=u"Zadnja promjena")

    def __unicode__(self):
        return unicode(self.zip_code)

    class Meta:
        verbose_name = _(u"Mjesto")
        verbose_name_plural = _(u"Mjesta")

class University(models.Model):
    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    last_update = models.DateTimeField(verbose_name=u"Zadnja promjena")

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u"Sveučilište")
        verbose_name_plural = _(u"Sveučilišta")

class College(models.Model):
    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    address = models.CharField(verbose_name=u'Adresa', max_length=255)
    place = models.ForeignKey(Place, verbose_name=u'Mjesto')
    university = models.ForeignKey(University, verbose_name=u'Sveučilište')
    last_update = models.DateTimeField(verbose_name=u"Zadnja promjena")

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u"Fakultet")
        verbose_name_plural = _(u"Fakulteti")

class Course(models.Model):
    name = models.CharField(verbose_name=u'Naziv', max_length=255)
    slug = models.SlugField(verbose_name=_(u"Slug/URL"), max_length=255)
    college = models.ForeignKey(College, verbose_name=u'Fakultet')
    pass_threshold = models.DecimalField(verbose_name=_(u"Prag za prolaz"), default=50, max_digits = 5, decimal_places = 2)
    description = models.TextField(verbose_name=u'Opis', null=True, blank=True)
    last_update = models.DateTimeField(verbose_name=u"Zadnja promjena")    

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u"Kolegij")
        verbose_name_plural = _(u"Kolegiji")

class Employee(models.Model):
    EMPLOYEE_TYPE = (
        ('A', _(u"Asistent")),
        ('P', _(u"Profesor")),    
    )
    title = models.CharField(verbose_name=u'Titula', max_length=40, null=True, blank=True)
    first_name = models.CharField(verbose_name=_(u"Ime"), max_length=255)
    last_name = models.CharField(verbose_name=_(u"Prezime"), max_length=255)
    email = models.EmailField(verbose_name='E-mail', max_length=255, unique=True)
    employee_type = models.CharField(verbose_name=_(u"Tip zaposlenika"), max_length=1, null=True, choices=EMPLOYEE_TYPE)
    last_update = models.DateTimeField(verbose_name=u"Zadnja promjena")

    def __unicode__(self):
        return unicode("%s %s" % (self.first_name, self.last_name))

    class Meta:
        verbose_name = _(u"Izvođač")
        verbose_name_plural = _(u"Izvođači")


class CourseEmployee(models.Model):
    course = models.ForeignKey(Course, verbose_name=u'Kolegij')
    employee = models.ForeignKey(Employee, verbose_name=u'Izvođač')
    last_update = models.DateTimeField(verbose_name=u"Zadnja promjena")

    def __unicode__(self):
        return unicode("%s %s" % (self.course.name, self.employee.last_name))

    class Meta:
        verbose_name = _(u"Izvođač kolegija")
        verbose_name_plural = _(u"Izvođači kolegija")      

university/forms.py
from django import forms

from organizer.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('student', 'date', 'course')

class SendMailForm(forms.Form):
    subject = forms.CharField(label="Predmet", max_length=100, required=True)
    message = forms.CharField(label="Poruka", widget=forms.Textarea, required=True)

templates/university/comment.html
<p style="margin:0px;"><span style="color:#04616E;">{{comment.student.first_name}} {{comment.student.last_name}}</span>: {{comment.text|safe}}
{% ifequal comment.student user  %} 
  <a class="delete_comment" href="#" data-id="{{comment.id}}"><i class="icon-trash"></i></a>
{% endifequal %} </p>
<div style="font-size:10px; margin-bottom: 10px;">{{comment.date}}</div>

<script>
$('.delete_comment').on('click',function(e){
        e.preventDefault();
        var clicked = $(this);

        alertify.set({ buttonReverse: true,
            labels: {
                ok     : "Da",
                cancel : "Ne"
        } });
        
        alertify.confirm("Jeste li sigurni da želite obrisati svoj komentar iz ove objave?", function (e) {
            if (e) {
                $.post("/delete-comment",{'comment_id':clicked.data('id')},function(msg){
                    location.reload();
                });
            } else {
                // user clicked "cancel"
            }
        });

        
    });
</script>

templates/university/comments.html
{% for comment in comments %}

<p style="margin:0px;"><span style="color:#04616E;">{{comment.student.first_name}} {{comment.student.last_name}}</span>: {{comment.text|safe}}
{% ifequal comment.student user  %} 
  <a class="delete_comment" href="#" data-id="{{comment.id}}"><i class="icon-trash"></i></a>
{% endifequal %} 
</p>
<div style="font-size:10px; margin-bottom: 10px;">{{comment.date}}</div>
    
{% endfor %}
<div class="new_comment{{post_id}}"></div>
<form>
<textarea style="margin-top:15px; width: 547px;" class="comment_text{{post_id}} span7" placeholder="Komentiraj" name="text" rows="2"></textarea>
<input type="hidden" name="post_id" value="{{post_id}}">
</form>

<script>
$('.comment_text{{post_id}}').keypress(function(e) {
      if (e.keyCode == 13 && !e.shiftKey) {
        e.preventDefault();
        if ($('.comment_text{{post_id}}').val()!=''){
          $.ajax({
            url: "add-comment/",
            data: $("form").serialize(),
            success: function (data, textStatus, jqXHR){
                $('.comment_text{{post_id}}').val('');
                $('.new_comment{{post_id}}').append($(data));
                var com_num = $('.comments_number{{post_id}}').html();
                $('.comments_number{{post_id}}').html(parseInt(com_num)+1);
            },
          });
        }
      }
    });

$('.delete_comment').on('click',function(e){
        e.preventDefault();
        var clicked = $(this);

        alertify.set({ buttonReverse: true,
            labels: {
                ok     : "Da",
                cancel : "Ne"
        } });
        
        alertify.confirm("Jeste li sigurni da želite obrisati svoj komentar iz ove objave?", function (e) {
            if (e) {
                $.post("/delete-comment",{'comment_id':clicked.data('id')},function(msg){
                    location.reload();
                });
            } else {
                // user clicked "cancel"
            }
        });

        
    });
</script>

templates/university/course.html
{% extends "base.html" %}


{% block page_specific_head %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/jquery.minicolors.css" />  
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.minicolors.js"></script>

<script>
$(document).ready(function() {
  $('.minicolors').minicolors({
      hide: function() {
          $('.course_color').css("background-color", this.value);
          $.post("/update-color",{'student_course_id':$('input').data('courseid'), 'color':this.value},function(msg){});
      }
  });
});
</script>
{% endblock %}

{% block top_navigation %}

{% endblock %}
                       

{% block content %}

<div class="main">
    <div class="left_side_wide">            
        <h2>{{student_course.course.name}}</h2>

        <h4>Opis kolegija</h4>
        {{student_course.course.description}}
        <br/>
        <br/>
        <h4>Izvođači kolegija</h4>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Titula</th>
              <th>Ime i prezime</th>
              <th>Tip</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for employee in course_employees %}
            <tr>
              <td>{{employee.employee.title}}</td>
              <td>{{employee.employee.first_name}} {{employee.employee.last_name}}</td>
              {% ifequal employee.employee.employee_type 'P' %} 
              <td>Profesor</td>
              {% else %}
              <td>Asistent</td>
              {% endifequal %}
              
              <td><a href="{% url 'send_mail' student_course.course.slug student_course.id employee.employee.id %}">Pošalji mail</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <br/>
        <h4>Literatura</h4>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Naziv</th>
              <th>Autori</th>
              <th>Opis</th>
            </tr>
          </thead>
          <tbody>
            {% for literature in literature %}
            <tr>
              <td>{{literature.name}}</td>
              <td>{{literature.authors}}</td>              
              <td>{{literature.description}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <br/>
        <h4>Aktivnosti</h4> 
            
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>Naziv</th>
                  <th>Datum</th>
                  <th>Vrsta aktivnosti</th>
                  <th>Mogući bodovi</th>
                  <th>Ostvareni bodovi</th>
                </tr>
              </thead>
              <tbody>
                {% for activity in activities %}
                <tr>
                  <td><a href="{{activity.get_url}}">{{activity.title}}</a></td>
                  <td>{{activity.start}}</td>
                  <td>{{activity.activity_type.name}}</td>
                  <td>{{activity.max_points}}</td>
                  <td>{{activity.achieved_points}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <a href="{% url 'new_activity' student_course.id %}"><i class="icon-plus"></i> Nova aktivnost</a>
        
    </div>  
    <div class="right_side_narrow">
      <ul style="width:220px; padding-bottom:30px;" class="nav nav-pills nav-stacked">
      {% for course in student_courses %}
      <li {% ifequal course student_course %}class="active"{% endifequal %}><a href="{% url 'course' course.course.slug course.id %}">{{course.course.name}}</a></li>            
      {% endfor %}

    </ul>
        Boja kolegija: <input class="minicolors" type="text" data-courseid="{{student_course.id}}" value="{{student_course.color}}"> 
        <div class="course_color" style="padding-top: 10px; margin-top:10px; background-color: {{student_course.color}};"></div>
        
    </div>              
</div>

{% if messages%}
    {% for message in messages %}
   <script type="text/javascript">
        log_message = (function () {
              alertify.log("{{ message }}");
        })()
    </script> 
    {% endfor %}
{% endif %}
    
{% endblock %}

templates/university/course_wall.html
{% extends "base.html" %}
{% load university_tags %}

{% block page_specific_head %}
<script type='text/javascript'>
$(document).ready(function(){
    var page_number = 1;

    $(".show_comments").click(function(){
        var clicked = $(this);
        if($(".comments"+clicked.data('id')).hasClass('loaded')){
            $(".comments"+clicked.data('id')).empty();
            $(".comments"+clicked.data('id')).removeClass('loaded');
        }
        else{
            $.ajax('post-comments/' ,
                    {
                        data: {
                            post_id: clicked.data('id'),
                            page: page_number,
                        },
                         
                        // whether this is a POST or GET request
                        type: "GET",
                        statusCode: {
                            200: function (data, textStatus, jqXHR){
                                page_number++;
                                $(".comments"+clicked.data('id')).html($(data));
                                $(".comments"+clicked.data('id')).addClass('loaded');
                            },
                        }
                    }

            );
            return false;

        }
        
    });

    $(".show_files").click(function(){
        var clicked = $(this);
        if($(".files"+clicked.data('id')).hasClass('loaded')){
            $(".files"+clicked.data('id')).empty();
            $(".files"+clicked.data('id')).removeClass('loaded');
        }
        else{
            $.ajax('post-files/' ,
                    {
                        data: {
                            post_id: clicked.data('id'),
                        },
                         
                        // whether this is a POST or GET request
                        type: "GET",
                        statusCode: {
                            200: function (data, textStatus, jqXHR){
                                $(".files"+clicked.data('id')).html($(data));
                                $(".files"+clicked.data('id')).addClass('loaded');

                            },
                        }
                    }

            );
            return false;
        }
    });
});
</script>
{% endblock %}

{% block content %}

<div class="main">
        
        <div class="left_side">
            <h2>{{student_course.course.name}} - Objave</h2>

            <ul class = "posts">
                {% for post in posts %}
                    <li>
                        <div class = "post_box">
                            <div class = "post_title">
                                {{post.student.first_name}} {{post.student.last_name}}
                                {% ifequal post.student user  %} 
                                     <a class="edit" href="{% url 'edit_post' post.course.course.slug post.course.id post.id %}"><i style="font-size:8px;" class="icon-edit"></i></a>
                                    <a class="delete" href="#" data-id="{{post.id}}"><i class="icon-trash"></i></a>
                                {% endifequal %} 
                                
                            </div> 

                            <div class = "post_date">
                                {{post.date}}
                            </div>
                            <div class = "post">
                                {{post.text|safe}}                          
                            </div>
                            {% get_comments_number post as comments_number %} 
                            {% get_post_files_number post as files_number %} 
                            <div class = "show_comments_label">
                                <a class="show_files" href="#" data-id="{{post.id}}"><i style="margin-top: -1px;" class="icon-file"></i> Datoteke (<span class="files_number{{post.id}}">{{files_number}}</span>)</a> 
                               <a class="show_comments" href="#" data-id="{{post.id}}"><i style="margin-top: -1px; margin-left:5px;" class="icon-comment"></i> Komentari (<span class="comments_number{{post.id}}">{{comments_number}}</span>)</a>
                            </div>
                            <div class="files{{post.id}}" style="font-size: 12px;" data-id="{{post.id}}">
                            </div> 
                            <div class="comments{{post.id}}" style="font-size: 12px;" data-id="{{post.id}}">
                            </div> 
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <div style="text-align: center; margin: 30px; clear: both">
            <span>
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">Prethodna</a>
                {% endif %}
                {% if posts %}
                    <span class="current">
                        Stranica {{ posts.number }} od {{ posts.paginator.num_pages }}
                    </span>
                {% endif %}
                
        
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">Sljedeća</a>
                {% endif %}
            </span>
            </div>
        </div>

        <div class="right_side">
            <ul style="width:220px; padding-bottom:30px;" class="nav nav-pills nav-stacked">
              {% for course in student_courses %}
              <li {% ifequal course student_course %}class="active"{% endifequal %}><a href="{% url 'course_wall' course.course.slug course.id %}">{{course.course.name}}</a></li>            
              {% endfor %}

            </ul>
                         
        </div>
        
                
</div>
{% if messages%}
    {% for message in messages %}
   <script type="text/javascript">
        log_message = (function () {
              alertify.log("{{ message }}");
        })()
    </script> 
    {% endfor %}
{% endif %}
    
{% endblock %}

templates/university/edit_post.html
{% extends "base.html" %}

{% block page_specific_head %}
{% endblock %}

{% block content %}

<div class="main">
    <div class="text-section">
        <h1>Objava</h1>
        <form action="" method="post" enctype="multipart/form-data" >{% csrf_token %}
            {% with form.text as f %}            
                <textarea class="span7" id="id_text" name="text" rows="6">{{f.value}}</textarea>
                <span class="error_txt">{{ f.errors }}</span>            
            {% endwith %}
        <br/>

        {% if files %}
        <p>Priložene datoteke:</p>
        <ul>
        {% for file in files %}

        <li><a href="{{file.filename.url}}">{{file.name}}</a><a class="delete_file" href="#" data-id="{{file.id}}"><i class="icon-trash"></i></a></li>
            
        {% endfor %}

        </ul>
        <br/>
        {% endif %}
        <!--http://www.fyneworks.com/jquery/multiple-file-upload/-->

        <input type="file" class="multi" name="files">        

        <br/>
        <input type="submit" name="submit" value="Spremi" class="button">
        </form>

    </div>
                
</div>
    
{% endblock %}

templates/university/post_files.html
{% if files %}
<p>Priložene datoteke:</p>
<ul>
{% for file in files %}

<li><a href="{{file.filename.url}}">{{file.name}}</a></li>
    
{% endfor %}

</ul>
<br/>
{% endif %}

templates/university/send_mail.html
{% extends "base.html" %}

{% block page_specific_head %}
{% endblock %}

{% block content %}

<div class="main">
    <div class="text-section">
        <h1>Pošalji mail</h1>
        <p>Za: {{employee.first_name}} {{employee.last_name}}</p>

        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
            {% with form.subject as f %}
                <label for="{{ f.html_name }}">{{ f.label }}:</label>
                {{ f }}
                <span class="error_txt">{{ f.errors }}</span>
            {% endwith %}
            {% with form.message as f %}
                <label for="{{ f.html_name }}">{{ f.label }}:</label>
                <textarea class="span7" id="id_message" name="message" rows="10">{{f.value|default_if_none:""}}</textarea>
                <span class="error_txt">{{ f.errors }}</span>
            {% endwith %}
            
            <br>
            <input type="submit" name="submit" value="Spremi" class="button">
        </form>

    </div>
                
</div>
    
{% endblock %}